# Site settings
title: Last Name in the Hat
header-img: img/home-bg2.jpg
email: lastnameinthehat@gmail.com
description: "Last Name in the Hat is a small game development team working on creating Kuraz!"
baseurl: ""
url: "http://lnith.github.io"
twitter_username: LNintheHat
github_username:
facebook_username:  LNitH

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
